/* empty css                      */import{S as L,N as y}from"./assets/vendor-BvPe3f8Z.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))h(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&h(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function h(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const i=document.querySelector(".hero__img-wrapper"),a=document.querySelector(".hero__arrow-btn--prev"),d=document.querySelector(".hero__arrow-btn--next"),c=[{id:1,title:"Abstract Dreams",creator:"Alex Morgan",image:"../img/hero/hero-1.jpg"},{id:2,title:"Digital Nature",creator:"Emma Wilson",image:"../img/hero/hero-2.jpg"},{id:3,title:"Neon Future",creator:"Daniel Smith",image:"../img/hero/hero-3.jpg"},{id:4,title:"Silent Space",creator:"Olivia Brown",image:"../img/hero/hero-4.jpg"},{id:5,title:"Cyber City",creator:"James Miller",image:"../img/hero/hero-5.jpg"}];let s=0;a.disabled=!0;d.addEventListener("click",b);function b(){a.disabled=!1,s+=1,s+2===c.length&&(d.disabled=!0),i.classList.add("is-changing"),setTimeout(()=>{i.innerHTML=u(c),i.classList.remove("is-changing")},300)}a.addEventListener("click",_);function _(){d.disabled=!1,s-=1,s===0&&(a.disabled=!0),i.classList.add("is-changing"),setTimeout(()=>{i.innerHTML=u(c),i.classList.remove("is-changing")},300)}function u(t){const o=t[s],n=t[s+1];return`<img
            class="hero__img hero__img--left"
            src="${o.image}"
            alt=""
          />
<svg class="hero__arrow">
          <use href="../img/sprite.svg#arrow"></use>
        </svg>
          <img
            class="hero__img hero__img--right"
            src="${n.image}"
            alt=""
          />
          `}i.innerHTML=u(c);new L(".swiper",{modules:[y],loop:!0,slidesPerView:"auto",centeredSlides:!0,spaceBetween:40,centerInsufficientSlides:!0,navigation:{prevEl:".weekly-slider-prev",nextEl:".weekly-slider-next"}});const m=document.querySelector(".nav__menu-button"),g=document.querySelector(".page"),f=document.querySelector(".mobile-menu");m.addEventListener("click",S);g.addEventListener("click",w);function w(t){t.target.classList.contains("page")&&p()}document.addEventListener("keydown",t=>{t.key==="Escape"&&p()});let v=0;f.addEventListener("touchstart",t=>{v=t.changedTouches[0].screenX});f.addEventListener("touchend",t=>{t.changedTouches[0].screenX-v>80&&p()});function S(){g.classList.add("is-menu-open"),m.classList.add("is-open"),document.body.classList.add("no-scroll")}function p(){g.classList.remove("is-menu-open"),m.classList.remove("is-open"),document.body.classList.remove("no-scroll")}
//# sourceMappingURL=index.js.map
