import heroNft from '../../img/hero/hero-nft.jpg';

export const nfts = [
  {
    id: 1,
    name: 'Viktor',
    image: heroNft,
    category: 'Art',
    collection: 'Viktor Collection',
    auctionEnd: '2026-08-16T19:04:00',
    currentBid: '1.25',
    isWeekly: true,
  },
  {
    id: 2,
    name: 'Cyber Ape',
    image: heroNft,
    category: 'PFP',
    collection: 'Cyber Apes',
    auctionEnd: '2026-08-16T12:45:00',
    currentBid: '2.40',
    isWeekly: true,
  },
  {
    id: 3,
    name: 'Meta Punk',
    image: heroNft,
    category: 'PFP',
    collection: 'Meta Punks',
    auctionEnd: '2026-08-14T21:20:00',
    currentBid: '0.85',
    isWeekly: true,
  },
  {
    id: 4,
    name: 'Space Girl',
    image: heroNft,
    category: 'Art',
    collection: 'Space Girls',
    auctionEnd: '2026-08-17T18:10:00',
    currentBid: '3.10',
    isWeekly: true,
  },
  {
    id: 5,
    name: 'Crypto Cat',
    image: heroNft,
    category: 'Animals',
    collection: 'Crypto Cats',
    auctionEnd: '2026-08-15T09:30:00',
    currentBid: '1.75',
    isWeekly: true,
  },
  {
    id: 6,
    name: 'Digital Soul',
    image: heroNft,
    category: 'Art',
    collection: 'Digital Souls',
    auctionEnd: '2026-08-18T14:00:00',
    currentBid: '4.20',
    isWeekly: true,
  },
  {
    id: 7,
    name: 'Neon Monkey',
    image: heroNft,
    category: 'PFP',
    collection: 'Neon Monkeys',
    auctionEnd: '2026-08-16T20:15:00',
    currentBid: '2.90',
    isWeekly: true,
  },
  {
    id: 8,
    name: 'Future Face',
    image: heroNft,
    category: 'Photography',
    collection: 'Future Faces',
    auctionEnd: '2026-08-19T11:45:00',
    currentBid: '1.05',
    isWeekly: true,
  },

  {
    id: 9,
    name: 'Golden Skull',
    image: heroNft,
    category: 'Art',
    collection: 'Golden Skulls',
    auctionEnd: '2026-08-20T16:30:00',
    currentBid: '2.15',
    isWeekly: false,
  },
  {
    id: 10,
    name: 'Cyber Warrior',
    image: heroNft,
    category: 'PFP',
    collection: 'Cyber Warriors',
    auctionEnd: '2026-08-21T13:20:00',
    currentBid: '3.45',
    isWeekly: false,
  },
  {
    id: 11,
    name: 'Dream Landscape',
    image: heroNft,
    category: 'Photography',
    collection: 'Dreamscapes',
    auctionEnd: '2026-08-22T18:45:00',
    currentBid: '1.80',
    isWeekly: false,
  },
  {
    id: 12,
    name: 'Pixel Hero',
    image: heroNft,
    category: 'Pixel Art',
    collection: 'Pixel Heroes',
    auctionEnd: '2026-08-20T22:15:00',
    currentBid: '0.95',
    isWeekly: false,
  },
  {
    id: 13,
    name: 'Moon Walker',
    image: heroNft,
    category: 'Art',
    collection: 'Moon Walkers',
    auctionEnd: '2026-08-23T11:30:00',
    currentBid: '2.65',
    isWeekly: false,
  },
  {
    id: 14,
    name: 'Crypto Dragon',
    image: heroNft,
    category: 'Animals',
    collection: 'Crypto Dragons',
    auctionEnd: '2026-08-24T15:10:00',
    currentBid: '5.20',
    isWeekly: false,
  },
  {
    id: 15,
    name: 'Robot Mind',
    image: heroNft,
    category: 'AI',
    collection: 'Robot Minds',
    auctionEnd: '2026-08-21T19:40:00',
    currentBid: '1.35',
    isWeekly: false,
  },
  {
    id: 16,
    name: 'Neon City',
    image: heroNft,
    category: 'Photography',
    collection: 'Neon Cities',
    auctionEnd: '2026-08-25T12:00:00',
    currentBid: '2.75',
    isWeekly: false,
  },
  {
    id: 17,
    name: 'Pixel Cat',
    image: heroNft,
    category: 'Pixel Art',
    collection: 'Pixel Animals',
    auctionEnd: '2026-08-22T17:20:00',
    currentBid: '0.65',
    isWeekly: false,
  },
  {
    id: 18,
    name: 'Galaxy Girl',
    image: heroNft,
    category: 'Art',
    collection: 'Galaxy Girls',
    auctionEnd: '2026-08-26T14:50:00',
    currentBid: '3.85',
    isWeekly: false,
  },
  {
    id: 19,
    name: 'Digital Tiger',
    image: heroNft,
    category: 'Animals',
    collection: 'Digital Beasts',
    auctionEnd: '2026-08-23T20:30:00',
    currentBid: '2.25',
    isWeekly: false,
  },
  {
    id: 20,
    name: 'Virtual World',
    image: heroNft,
    category: 'Metaverse',
    collection: 'Virtual Worlds',
    auctionEnd: '2026-08-27T10:45:00',
    currentBid: '4.60',
    isWeekly: false,
  },

  {
    id: 21,
    name: 'Cyber Samurai',
    image: heroNft,
    category: 'PFP',
    collection: 'Cyber Warriors',
    auctionEnd: '2026-08-28T16:15:00',
    currentBid: '3.75',
    isWeekly: false,
  },
  {
    id: 22,
    name: 'Abstract Mind',
    image: heroNft,
    category: 'Abstract',
    collection: 'Abstract Minds',
    auctionEnd: '2026-08-29T13:40:00',
    currentBid: '1.90',
    isWeekly: false,
  },
  {
    id: 23,
    name: 'Rainbow World',
    image: heroNft,
    category: 'Art',
    collection: 'Rainbow Worlds',
    auctionEnd: '2026-08-30T18:00:00',
    currentBid: '2.35',
    isWeekly: false,
  },
  {
    id: 24,
    name: 'Pixel Warrior',
    image: heroNft,
    category: 'Pixel Art',
    collection: 'Pixel Heroes',
    auctionEnd: '2026-08-31T21:10:00',
    currentBid: '1.15',
    isWeekly: false,
  },
  {
    id: 25,
    name: 'Space Explorer',
    image: heroNft,
    category: 'Metaverse',
    collection: 'Space Explorers',
    auctionEnd: '2026-09-01T12:25:00',
    currentBid: '3.60',
    isWeekly: false,
  },
  {
    id: 26,
    name: 'Electric Soul',
    image: heroNft,
    category: 'AI',
    collection: 'Digital Souls',
    auctionEnd: '2026-09-02T17:45:00',
    currentBid: '2.80',
    isWeekly: false,
  },
  {
    id: 27,
    name: 'Blue Planet',
    image: heroNft,
    category: 'Photography',
    collection: 'Blue Planet',
    auctionEnd: '2026-09-03T19:30:00',
    currentBid: '1.55',
    isWeekly: false,
  },
  {
    id: 28,
    name: 'Golden Ape',
    image: heroNft,
    category: 'PFP',
    collection: 'Cyber Apes',
    auctionEnd: '2026-09-04T14:15:00',
    currentBid: '4.10',
    isWeekly: false,
  },
  {
    id: 29,
    name: 'Digital Flower',
    image: heroNft,
    category: 'Art',
    collection: 'Digital Nature',
    auctionEnd: '2026-09-05T11:00:00',
    currentBid: '0.90',
    isWeekly: false,
  },
  {
    id: 30,
    name: 'Future Robot',
    image: heroNft,
    category: 'AI',
    collection: 'Robot Minds',
    auctionEnd: '2026-09-06T20:20:00',
    currentBid: '3.25',
    isWeekly: false,
  },
];

export const weeklyNfts = nfts.filter(nft => nft.isWeekly);
